version: "3"
services:
  crispy-ruby:
    container_name: "crispy-ruby"
    build:
      dockerfile: "./docker/Dockerfile"
      context: "./"
    links:
      - "crispy-mariadb:mariadb.host"
      - "crispy-redis:redis.host"
    environment:
      - EMAIL_PORT
      - EMAIL_USERNAME
      - EMAIL_PASSWORD
      - DATABASE_URL
      - APP_SECRET
      - REDIS_URL
      - EMAIL_FROM
    ports:
      - 3000:3000
    volumes:
      - "./:/crispy-octo"
    restart: always

  crispy-resque:
    container_name: "crispy-resque"
    build:
      dockerfile: "./docker/Dockerfile"
      context: "./"
    links:
      - "crispy-mariadb:mariadb.host"
      - "crispy-redis:redis.host"
    environment:
      - EMAIL_PORT
      - EMAIL_USERNAME
      - EMAIL_PASSWORD
      - DATABASE_URL
      - REDIS_URL
      - APP_SECRET
      - EMAIL_FROM
    command: bundle exec rake environment resque:work QUEUE=*
    volumes:
      - "./:/crispy-octo"
    restart: always
  crispy-mariadb:
    image: "mariadb:10.6"
    container_name: "crispy-mariadb"
    volumes:
      - "._mysql_data_dir/:/var/lib/mysql"
    ports:
      - 3307:3306
    environment:
      - MARIADB_DATABASE
      - MARIADB_PASSWORD
      - MARIADB_USER
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    restart: always
  crispy-redis:
    image: "redis:alpine"
    container_name: "crispy-redis"
    restart: always
