apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: richflor/crispy-hetic
        ports:
        - containerPort: 3000
        resources:
            requests:
              cpu: 250m
              memory: 512M
            limits:
              cpu: 250m
              memory: 512M
        env:
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MARIADB_DATABASE
            - name: MARIADB_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MARIADB_HOST
            - name: MARIADB_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MARIADB_PORT
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: crispy-secret
                  key: MARIADB_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crispy-secret
                  key: MARIADB_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DATABASE_URL

            - name: EMAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: EMAIL_PORT
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: crispy-secret
                  key: MARIADB_PASSWORD
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crispy-secret
                  key: MARIADB_PASSWORD
            - name: EMAIL_FROM
              value: "bienechris@hetic.fr"
            
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: REDIS_PORT
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: crispy-secret
                  key: REDIS_USERNAME
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crispy-secret
                  key: REDIS_PASSWORD
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: REDIS_URL
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000